### PR TITLE
Bot pr arm osx h742397

### PR DESCRIPTION
**Pull request by douglowe**

### CODE REVIEW

**Comment by xiki-tempula** [comment]
Sorry I set the target branch wrongly. I think we shall just merge this one and see if it works in the PR in the main repo? The bot does not seems to have any action configured.

**Comment by douglowe** [comment]
We need to delete this branch I think (see my question in the issue I just created), and try pushing your change again.

Can you copy the bot PR again - adding the one if statement change to stop the compilation of the arm64 openmpi branches - and submit a new PR from your own account to the `main` branch on this repository?

**Comment by xiki-tempula** [comment]
Sorry I'm a bit confused. Do you mean delete the branch regro-cf-autotick-bot:bot-pr_arm_osx_h742397? I think regro-cf-autotick-bot created this branch?
When you say to the main branch, do you mean the main branch in regro-cf-autotick-bot/gromacs-feedstock?

**Comment by douglowe** [comment]
I mean that you should create a personal copy of the gromacs-feedstock repository, as you did before - but when you create the PR make the target the main branch in conda-forge/gromacs-feedstock.

**Pull request closed without merging**
